#!/bin/bash
#
# A simple installer for the Certbot Cloudflare DNS docker image.
#
# Copyright (C) 2023 Alan Doyle
#
# https://github.com/alandoyle/docker-cloudflare-certbot
#
################################################################################
#
EMAIL=
APITOKEN=
#
################################################################################
#
# Root check
#
if [ `id -u` -ne 0 ] ; then
    echo "ERROR: This script needs to be run as root or using sudo."
    exit 99
fi
################################################################################
#
# Download the git repository
#
if [ ! -d /srv/docker-cloudflare-certbot ] ; then
    cd /srv
    git clone https://github.com/alandoyle/docker-cloudflare-certbot >/dev/null
fi
#
################################################################################
#
# Ensure up-to-date
#
cd /srv/docker-cloudflare-certbot
git pull >/dev/null
chmod a+x /srv/docker-cloudflare-certbot/bin/*
chmod a+x /srv/docker-cloudflare-certbot/install
mkdir -p /var/log/letsencrypt
#
################################################################################
#
# Ensure we have an email address as that's required for use with Lets Encrypt
#
[ -f /srv/docker-cloudflare-certbot/.env ] && . /srv/docker-cloudflare-certbot/.env
while [ -z ${TMPEMAIL} ] ; do
    read -p "What email address do you wish to use with Lets Encrypt [${EMAIL}] ? " TMPEMAIL
    [ -z ${TMPEMAIL} ] && TMPEMAIL=${EMAIL}
done
echo EMAIL=${TMPEMAIL}
echo "EMAIL=${TMPEMAIL}" > /srv/docker-cloudflare-certbot/.env
#
################################################################################
#
# Ensure we have an API Token to use with Cloudflare DNS
#
if [ -f /srv/docker-cloudflare-certbot/cloudflare/credentials ] ; then
    APITOKEN=`grep dns_cloudflare_api_token /srv/docker-cloudflare-certbot/cloudflare/credentials | cut -d= -f2 | sed -e 's/^[ \t]*//'`
fi
while [ -z ${TMPAPITOKEN} ] ; do
    read -p "What is the API Token to use with Cloudflare [${APITOKEN}] ? " TMPAPITOKEN
    [ -z ${TMPAPITOKEN} ] && TMPAPITOKEN=${APITOKEN}
done
[ ! -d /srv/docker-cloudflare-certbot/cloudflare ] && mkdir -p /srv/docker-cloudflare-certbot/cloudflare

echo APITOKEN=${TMPAPITOKEN}
echo -e "# CloudFlare API token information\ndns_cloudflare_api_token = ${TMPAPITOKEN}" > /srv/docker-cloudflare-certbot/cloudflare/credentials
chmod 600 /srv/docker-cloudflare-certbot/cloudflare/credentials
#
################################################################################
#
# Create sumbolic links
#
ln -sf /srv/docker-cloudflare-certbot/bin/gen-cert     /usr/local/bin/gen-cert
ln -sf /srv/docker-cloudflare-certbot/bin/renew-certs  /usr/local/bin/renew-certs
ln -sf /srv/docker-cloudflare-certbot/bin/test-certbot /usr/local/bin/test-certbot
#
################################################################################
#
# Create crontab
#
(crontab -l 2>/dev/null; echo "0 3 * * * /usr/local/bin/renew-certs > /var/log/renew-certs.log") | crontab -
#
################################################################################
#
# Complete
unset EMAIL
unset APITOKEN
echo Complete.
#
################################################################################
