#!/bin/bash
#
# A simple installer for Certbot with Cloudflare DNS-01 auth method.
#
# Copyright (C) 2023-2025 Alan Doyle
#
# https://github.com/alandoyle/docker-cloudflare-certbot
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see http://www.gnu.org/licenses/.
#
# Install using:
#     sudo bash -c "$(wget -qLO - https://raw.githubusercontent.com/alandoyle/docker-cloudflare-certbot/main/install)"
# or
#     sudo bash -c "$(curl -sSfL https://raw.githubusercontent.com/alandoyle/docker-cloudflare-certbot/main/install)"
#
################################################################################
#
EMAIL=
APITOKEN=
#
################################################################################
#
# Root check
#
if [ `id -u` -ne 0 ] ; then
    echo "ERROR: This script needs to be run as root or using sudo."
    exit 99
fi
#
################################################################################
#
# Docker Check
#
if [ ! -f /usr/bin/docker ] ; then
    echo "ERROR: This script needs 'docker' installed."
    exit 99
fi
################################################################################
#
# Download the git repository
#
if [ ! -d /srv/docker-cloudflare-certbot ] ; then
    cd /srv
    git clone https://github.com/alandoyle/docker-cloudflare-certbot >/dev/null
fi
#
################################################################################
#
# Ensure up-to-date
#
cd /srv/docker-cloudflare-certbot
git pull >/dev/null
mkdir -p /var/log/letsencrypt
apt-get update >/dev/null
#
################################################################################
#
# Create directory structure
#
[ ! -d /etc/certbot-cf/restart ] && mkdir -p /etc/certbot-cf/restart
[ ! -f /etc/certbot-cf/restart/nginx ] && echo "# systemctl restart nginx" > /etc/certbot-cf/restart/nginx
[ ! -f /etc/certbot-cf/restart/apache ] && echo "# systemctl restart apache" > /etc/certbot-cf/restart/apache
[ ! -f /etc/certbot-cf/restart/webmin ] && echo "# /etc/webmin/restart" > /etc/certbot-cf/restart/webmin#
#
################################################################################
#
# Migrate credentials
#
if [ -f /srv/docker-cloudflare-certbot/cloudflare/credentials ] ; then
    mv /srv/docker-cloudflare-certbot/cloudflare/credentials /etc/certbot-cf/credentials
    rm -rf /srv/docker-cloudflare-certbot/cloudflare
fi
#
################################################################################
#
# Ensure we have an email address as that's required for use with Lets Encrypt
#
[ -f /srv/docker-cloudflare-certbot/.env ] && . /srv/docker-cloudflare-certbot/.env
while [ -z ${TMPEMAIL} ] ; do
    read -p "What email address do you wish to use with Lets Encrypt [${EMAIL}] ? " TMPEMAIL
    [ -z ${TMPEMAIL} ] && TMPEMAIL=${EMAIL}
done
echo EMAIL=${TMPEMAIL}
echo "EMAIL=${TMPEMAIL}" > /srv/docker-cloudflare-certbot/.env
#
################################################################################
#
# Ensure we have an API Token to use with Cloudflare DNS
#
if [ -f /etc/certbot-cf/credentials ] ; then
    APITOKEN=`grep dns_cloudflare_api_token /etc/certbot-cf/credentials | cut -d= -f2 | sed -e 's/^[ \t]*//'`
fi
while [ -z ${TMPAPITOKEN} ] ; do
    read -p "What is the API Token to use with Cloudflare [${APITOKEN}] ? " TMPAPITOKEN
    [ -z ${TMPAPITOKEN} ] && TMPAPITOKEN=${APITOKEN}
done

echo APITOKEN=${TMPAPITOKEN}
echo -e "# CloudFlare API token information\ndns_cloudflare_api_token = ${TMPAPITOKEN}" > /etc/certbot-cf/credentials
chmod 600 /etc/certbot-cf/credentials
#
################################################################################
#
# Replace old symbolic links
#
[ -h /usr/local/bin/gen-cert ]     && rm -f /usr/local/bin/gen-cert
[ -h /usr/local/bin/renew-certs ]  && rm -f /usr/local/bin/renew-certs
[ -h /usr/local/bin/test-certbot ] && rm -f /usr/local/bin/test-certbot

cp -f /srv/docker-cloudflare-certbot/bin/gen-cert     /usr/local/bin/gen-cert
cp -f /srv/docker-cloudflare-certbot/bin/renew-certs  /usr/local/bin/renew-certs
cp -f /srv/docker-cloudflare-certbot/bin/test-certbot /usr/local/bin/test-certbot

chmod a+x /usr/local/bin/*cert*
#
################################################################################
#
# Remove crontab
#
(crontab -l | grep -v renew-certs) | crontab -
#
################################################################################
#
# Stop old Certbot systemd service
#
systemctl stop certbot.timer 2>/dev/null
systemctl disable certbot.timer 2>/dev/null
systemctl stop certbot.service 2>/dev/null
systemctl disable certbot.service 2>/dev/null
#
# New Cloudflare systemd timer
cat << EOF | tee  /usr/lib/systemd/system/certbot-cf.timer >/dev/null
[Unit]
Description=Run Certbot (Cloudflare DNS-01) twice daily

[Timer]
OnCalendar=*-*-* 00,12:00:00
RandomizedDelaySec=43200
Persistent=true

[Install]
WantedBy=timers.target
EOF
#
# New Cloudflare systemd service
cat << EOF | tee  /usr/lib/systemd/system/certbot-cf.service >/dev/null
[Unit]
Description=Certbot (Cloudflare DNS-01)
Documentation=file:///usr/share/doc/python-certbot-doc/html/index.html
Documentation=https://certbot.eff.org/docs
[Service]
Type=oneshot
ExecStart=/usr/local/bin/renew-certs > /var/log/letsencrypt/renew-certs.log
PrivateTmp=true
EOF
#
# Refresh systemd
systemctl daemon-reload
#
# Start timer
systemctl enable certbot-cf.timer
systemctl start certbot-cf.timer
#
################################################################################
#
# Complete
unset EMAIL
unset APITOKEN
echo Complete.
#
################################################################################
